### ISSUE TITLE
dev.off() should show something in client

### ISSUE THREAD

**Issue by jeroen** [nx10/httpgd#23]
If we do:

```r
> dev.off()
Server closing... Closed.
httpgd
     2
```

The client just dies. It would be nice if the html/js client would somehow get a notification that the device has been closed (and stop polling 😄 )

**Comment by nx10** [comment]
Thank you for your suggestion.
I've been putting it off a much needed rewrite of the html/js client for a while now because I am currently working on server side websocket integration (faster updates, no polling) for which the client will have to change yet again.
I was planning on showing a transparent gray overlay or something similar to indicate lost connection.

**Comment by nx10** [comment]
The client will now detect and show disconnected status.
